### ISSUE TITLE
执行celery -A ApiManager.tasks worker -l info报错

### ISSUE THREAD

**Issue by bzc128** [JoyMobileDevelopmentTeam/Joy_QA_Platform#3]
[root@localhost Joy_QA_Platform]# celery -A ApiManager.tasks worker -l info
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/base.py", line 269, in execute_from_commandline
    self.on_concurrency_setup()
  File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/celery.py", line 539, in on_concurrency_setup
    self.load_extension_commands()
  File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/celery.py", line 543, in load_extension_commands
    self.register_command).load()
  File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/base.py", line 138, in load
    for name, cls in imports.load_extension_classes(self.namespace):
  File "/usr/local/python3/lib/python3.6/site-packages/celery/utils/imports.py", line 156, in load_extension_classes
    cls = symbol_by_name(class_name)
  File "/usr/local/python3/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/python3/lib/python3.6/site-packages/flower/command.py", line 18, in <module>
    from .app import Flower
  File "/usr/local/python3/lib/python3.6/site-packages/flower/app.py", line 15, in <module>
    from .urls import handlers
  File "/usr/local/python3/lib/python3.6/site-packages/flower/urls.py", line 9, in <module>
    from .api import tasks
  File "/usr/local/python3/lib/python3.6/site-packages/flower/api/tasks.py", line 81, in <module>
    class TaskApply(BaseTaskHandler):
  File "/usr/local/python3/lib/python3.6/site-packages/flower/api/tasks.py", line 83, in TaskApply
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'

**Comment by WuCh1k1n** [comment]
> [root@localhost Joy_QA_Platform]# celery -A ApiManager.tasks worker -l info
> Traceback (most recent call last):
> File "/usr/local/bin/celery", line 10, in 
> sys.exit(main())
> File "/usr/local/python3/lib/python3.6/site-packages/celery/**main**.py", line 16, in main
> _main()
> File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
> cmd.execute_from_commandline(argv)
> File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
> super(CeleryCommand, self).execute_from_commandline(argv)))
> File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/base.py", line 269, in execute_from_commandline
> self.on_concurrency_setup()
> File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/celery.py", line 539, in on_concurrency_setup
> self.load_extension_commands()
> File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/celery.py", line 543, in load_extension_commands
> self.register_command).load()
> File "/usr/local/python3/lib/python3.6/site-packages/celery/bin/base.py", line 138, in load
> for name, cls in imports.load_extension_classes(self.namespace):
> File "/usr/local/python3/lib/python3.6/site-packages/celery/utils/imports.py", line 156, in load_extension_classes
> cls = symbol_by_name(class_name)
> File "/usr/local/python3/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
> module = imp(module_name, package=package, **kwargs)
> File "/usr/local/python3/lib/python3.6/importlib/**init**.py", line 126, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 994, in _gcd_import
> File "", line 971, in _find_and_load
> File "", line 955, in _find_and_load_unlocked
> File "", line 665, in _load_unlocked
> File "", line 678, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "/usr/local/python3/lib/python3.6/site-packages/flower/command.py", line 18, in 
> from .app import Flower
> File "/usr/local/python3/lib/python3.6/site-packages/flower/app.py", line 15, in 
> from .urls import handlers
> File "/usr/local/python3/lib/python3.6/site-packages/flower/urls.py", line 9, in 
> from .api import tasks
> File "/usr/local/python3/lib/python3.6/site-packages/flower/api/tasks.py", line 81, in 
> class TaskApply(BaseTaskHandler):
> File "/usr/local/python3/lib/python3.6/site-packages/flower/api/tasks.py", line 83, in TaskApply
> @web.asynchronous
> AttributeError: module 'tornado.web' has no attribute 'asynchronous'

tornado 6.0以上的版本去除了这个属性
